### ISSUE TITLE
Benchmark fails to run in Safari

### ISSUE THREAD

**Issue by davehunt** [mozilla-spidermonkey/matrix-react-bench#4]
Whilst testing to see which of our performance tests are able to run in Safari on macOS I discovered the following error for this benchmark:

> 15:04:51    ERROR -  raptor-browsertime Error: Browsertime failed to run
15:04:51     INFO -  raptor-browsertime Info: [browsertime] Executing script return (function() {
15:04:51     INFO -  raptor-browsertime Info:   const supported = PerformanceObserver.supportedEntryTypes;
15:04:51     INFO -  raptor-browsertime Info:   if (!supported || supported.indexOf('layout-shift') === -1) {
15:04:51     INFO -  raptor-browsertime Info:     return;
15:04:51     INFO -  raptor-browsertime Info:   }
15:04:51     INFO -  raptor-browsertime Info:   // See https://web.dev/layout-instability-api
15:04:51     INFO -  raptor-browsertime Info:   // https://github.com/mmocny/web-vitals/wiki/Snippets-for-LSN-using-PerformanceObserver#max-session-gap1s-limit5s
15:04:51     INFO -  raptor-browsertime Info:   let max = 0;
15:04:51     INFO -  raptor-browsertime Info:   let curr = 0;
15:04:51     INFO -  raptor-browsertime Info:   let firstTs = Number.NEGATIVE_INFINITY;
15:04:51     INFO -  raptor-browsertime Info:   let  prevTs = Number.NEGATIVE_INFINITY;
15:04:51     INFO -  raptor-browsertime Info:   const observer = new PerformanceObserver(list => {});
15:04:51     INFO -  raptor-browsertime Info:   observer.observe({ type: 'layout-shift', buffered: true });
15:04:51     INFO -  raptor-browsertime Info:   const list = observer.takeRecords();
15:04:51     INFO -  raptor-browsertime Info:   for (let entry of list) {
15:04:51     INFO -  raptor-browsertime Info:     if (entry.hadRecentInput) {
15:04:51     INFO -  raptor-browsertime Info:       continue;
15:04:51     INFO -  raptor-browsertime Info:     }
15:04:51     INFO -  raptor-browsertime Info:     if (entry.startTime - firstTs > 5000 || entry.startTime - prevTs > 1000) {
15:04:51     INFO -  raptor-browsertime Info:       firstTs = entry.startTime;
15:04:51     INFO -  raptor-browsertime Info:       curr = 0;
15:04:51     INFO -  raptor-browsertime Info:     }
15:04:51     INFO -  raptor-browsertime Info:     prevTs = entry.startTime;
15:04:51     INFO -  raptor-browsertime Info:     curr += entry.value;
15:04:51     INFO -  raptor-browsertime Info:     max = Math.max(max, curr);
15:04:51     INFO -  raptor-browsertime Info:   }
15:04:51     INFO -  raptor-browsertime Info:   return max;
15:04:51     INFO -  raptor-browsertime Info: })();
15:04:51     INFO -  raptor-browsertime Info:
15:04:51 CRITICAL -  raptor-browsertime Critical: [browsertime] Failed to execute user script: TimeoutError
15:04:51    ERROR -  Traceback (most recent call last):
15:04:51     INFO -    File "/Users/dave/workspace/mozilla-unified/testing/raptor/raptor/raptor.py", line 206, in <module>
15:04:51     INFO -      main()
15:04:51     INFO -    File "/Users/dave/workspace/mozilla-unified/testing/raptor/raptor/raptor.py", line 152, in main
15:04:51     INFO -      success = raptor.run_tests(raptor_test_list, raptor_test_names)
15:04:51     INFO -    File "/Users/dave/workspace/mozilla-unified/testing/raptor/raptor/perftest.py", line 469, in run_tests
15:04:51     INFO -      self.run_test(test, timeout=int(test.get("page_timeout")))
15:04:51     INFO -    File "/Users/dave/workspace/mozilla-unified/testing/raptor/raptor/browsertime/base.py", line 803, in run_test
15:04:51     INFO -      raise Exception(self.browsertime_failure)
15:04:51     INFO -  Exception: [browsertime] Failed to execute user script: TimeoutError
15:04:51    ERROR - Return code: 1

**Comment by moztcampbell** [comment]
This error is coming out of the 'web-vitals' package used by 'sentry' used by the 'matrix-react-sdk' we use for the benchmark. I'm not sure why this doesn't cause trouble for matrix chat itself in safari?
